/**
 * Post-meeting analysis: fixed-section brief generated by the active AI provider.
 * Triggered automatically on ingest and when the user marks a meeting as ended.
 */
import { createServerFn } from "@tanstack/react-start";
import type {
  AnalyzedActionItem,
  MeetingAnalysis,
  MeetingRecord,
  ProposedPatch,
  RetrievedChunk,
} from "./types.ts";

export type AiProviderId = "grok" | "claude" | "custom";

type AiCallConfig = {
  providerId?: AiProviderId;
  apiKey?: string;
  model?: string;
  baseUrl?: string;
};

type AnalyzeInput = {
  meeting: Pick<
    MeetingRecord,
    | "id"
    | "title"
    | "startedAt"
    | "attendees"
    | "summary"
    | "decisions"
    | "actionItems"
    | "sourceFile"
    | "platform"
  >;
  /** Raw captured transcript (speaker turns). */
  transcript?: string;
  /** Optional linked-repo code context (already retrieved). */
  codeContext?: RetrievedChunk[];
  ai?: AiCallConfig;
};

function resolveProvider(ai?: AiCallConfig): {
  providerId: AiProviderId;
  apiKey: string;
  model: string;
  baseUrl: string;
} {
  const providerId: AiProviderId =
    ai?.providerId === "claude" || ai?.providerId === "custom" || ai?.providerId === "grok"
      ? ai.providerId
      : "grok";

  const clientKey = (ai?.apiKey ?? "").trim();
  const envGrok = (process.env.XAI_API_KEY ?? "").trim();
  const envClaude = (process.env.ANTHROPIC_API_KEY ?? "").trim();
  const envOpenAi = (process.env.OPENAI_API_KEY ?? "").trim();

  let apiKey = clientKey;
  if (!apiKey) {
    if (providerId === "grok") apiKey = envGrok;
    else if (providerId === "claude") apiKey = envClaude;
    else apiKey = envOpenAi;
  }

  const defaults: Record<AiProviderId, { model: string; baseUrl: string }> = {
    grok: { model: "grok-4.5", baseUrl: "https://api.x.ai/v1" },
    claude: { model: "claude-sonnet-4-5", baseUrl: "https://api.anthropic.com" },
    custom: { model: "gpt-4o", baseUrl: "https://api.openai.com/v1" },
  };

  const model = (ai?.model ?? "").trim() || defaults[providerId].model;
  const baseUrl = ((ai?.baseUrl ?? "").trim() || defaults[providerId].baseUrl).replace(
    /\/+$/,
    "",
  );

  return { providerId, apiKey, model, baseUrl };
}

async function callOpenAiCompatible(
  baseUrl: string,
  apiKey: string,
  model: string,
  prompt: string,
): Promise<{ text: string; model: string }> {
  const res = await fetch(`${baseUrl}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      max_tokens: 2200,
      temperature: 0.2,
      messages: [{ role: "user", content: prompt }],
    }),
    signal: AbortSignal.timeout(45000),
  });
  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    throw new Error(`Provider HTTP ${res.status}: ${errText.slice(0, 200)}`);
  }
  const body = (await res.json()) as {
    choices?: { message?: { content?: string } }[];
    model?: string;
  };
  const text = body.choices?.[0]?.message?.content?.trim() ?? "";
  if (!text) throw new Error("Empty completion from provider");
  return { text, model: body.model || model };
}

async function callClaude(
  apiKey: string,
  model: string,
  prompt: string,
): Promise<{ text: string; model: string }> {
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model,
      max_tokens: 2200,
      temperature: 0.2,
      messages: [{ role: "user", content: prompt }],
    }),
    signal: AbortSignal.timeout(45000),
  });
  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    throw new Error(`Claude HTTP ${res.status}: ${errText.slice(0, 200)}`);
  }
  const body = (await res.json()) as {
    content?: { type?: string; text?: string }[];
    model?: string;
  };
  const text =
    body.content
      ?.filter((b) => b.type === "text" && b.text)
      .map((b) => b.text)
      .join("\n")
      .trim() ?? "";
  if (!text) throw new Error("Empty completion from Claude");
  return { text, model: body.model || model };
}

function buildAnalysisPrompt(
  meeting: AnalyzeInput["meeting"],
  codeContext: RetrievedChunk[],
  transcript: string,
): string {
  const actions = meeting.actionItems
    .map((a) => `- ${a.owner}: ${a.text}`)
    .join("\n");
  const decisions = meeting.decisions.map((d) => `- ${d}`).join("\n");

  const codeBlock =
    codeContext.length > 0
      ? codeContext
          .slice(0, 6)
          .map(
            (c, i) =>
              `[Code ${i + 1}] ${c.sourceFile}\n${c.text.slice(0, 900)}`,
          )
          .join("\n\n")
      : "(no linked repository code available)";

  return `You are a meeting analyst for a product/engineering team. Produce a concise, structured post-meeting brief.

Return ONLY valid JSON (no markdown fences, no commentary) with exactly these keys:
{
  "objective": "1-3 sentences: primary goal / why this meeting happened",
  "topics": ["main topic 1", "main topic 2"],
  "solutions": ["solution proposed for a problem that came up"],
  "keyDecisions": ["decision 1", "decision 2"],
  "actionItems": [{"owner": "name or unassigned", "text": "what", "priority": "high|medium|low"}],
  "technicalImplications": ["code / pipeline / architecture implication"],
  "proposedPatches": [{"file": "path/to/file", "description": "what to change", "diff": "unified diff or clear before/after snippet"}],
  "risks": ["risk or open question"],
  "nextSteps": ["concrete next step"]
}

Rules:
1. Use ONLY the meeting content, transcript, and any code context provided. Do not invent facts.
2. Keep every list short (max 6 items). Prefer clarity over volume.
3. topics: the main subjects actually discussed — not a restatement of the title.
4. solutions: concrete fixes or approaches people proposed for problems in the meeting. Empty array if none.
5. proposedPatches: only include if the meeting clearly discussed a concrete code or pipeline change AND code context is present. Otherwise [].
6. If a field has nothing useful, return an empty array or a short honest note in objective.
7. priority on actionItems is optional; omit if unclear.
8. Relate technical notes to the linked project when code context is present.

Meeting
-------
Title: ${meeting.title}
Platform: ${meeting.platform}
Started: ${meeting.startedAt}
Source: ${meeting.sourceFile}
Attendees: ${meeting.attendees.join(", ") || "(none listed)"}

Summary:
${meeting.summary || "(none)"}

Decisions:
${decisions || "(none)"}

Action items:
${actions || "(none)"}

Transcript:
${transcript.trim() || "(none)"}

Linked repository code (if any):
${codeBlock}

JSON:`;
}

function safeParseAnalysis(raw: string, model: string): MeetingAnalysis {
  // Strip accidental markdown fences
  let text = raw.trim();
  if (text.startsWith("```")) {
    text = text.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "");
  }

  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(text) as Record<string, unknown>;
  } catch {
    // Fallback: put the whole response into objective so the UI still shows something
    return {
      objective: raw.slice(0, 600),
      topics: [],
      solutions: [],
      keyDecisions: [],
      actionItems: [],
      technicalImplications: [],
      proposedPatches: [],
      risks: [],
      nextSteps: [],
      generatedAt: new Date().toISOString(),
      model,
    };
  }

  const asStringArray = (v: unknown): string[] =>
    Array.isArray(v) ? v.filter((x): x is string => typeof x === "string").slice(0, 8) : [];

  const actionItems: AnalyzedActionItem[] = Array.isArray(parsed.actionItems)
    ? parsed.actionItems
        .filter((x): x is Record<string, unknown> => !!x && typeof x === "object")
        .map((x) => {
          const rawPriority = x.priority;
          const priority: AnalyzedActionItem["priority"] =
            rawPriority === "high" || rawPriority === "medium" || rawPriority === "low"
              ? rawPriority
              : undefined;
          return {
            owner: typeof x.owner === "string" ? x.owner : "unassigned",
            text: typeof x.text === "string" ? x.text : "",
            priority,
          };
        })
        .filter((a) => a.text)
        .slice(0, 8)
    : [];

  const proposedPatches: ProposedPatch[] = Array.isArray(parsed.proposedPatches)
    ? parsed.proposedPatches
        .filter((x): x is Record<string, unknown> => !!x && typeof x === "object")
        .map((x) => ({
          file: typeof x.file === "string" ? x.file : "unknown",
          description: typeof x.description === "string" ? x.description : "",
          diff: typeof x.diff === "string" ? x.diff : "",
        }))
        .filter((p) => p.description || p.diff)
        .slice(0, 4)
    : [];

  return {
    objective:
      typeof parsed.objective === "string" && parsed.objective.trim()
        ? parsed.objective.trim()
        : "No clear objective extracted.",
    topics: asStringArray(parsed.topics),
    solutions: asStringArray(parsed.solutions),
    keyDecisions: asStringArray(parsed.keyDecisions),
    actionItems,
    technicalImplications: asStringArray(parsed.technicalImplications),
    proposedPatches,
    risks: asStringArray(parsed.risks),
    nextSteps: asStringArray(parsed.nextSteps),
    generatedAt: new Date().toISOString(),
    model,
  };
}

export type AnalyzeResult =
  | { ok: true; analysis: MeetingAnalysis }
  | { ok: false; error: string };

export const analyzeMeeting = createServerFn({ method: "POST" })
  .validator((input: AnalyzeInput) => {
    const m = input?.meeting;
    if (!m || typeof m.id !== "string" || typeof m.title !== "string") {
      throw new Error("meeting is required");
    }
    const ai = input?.ai
      ? {
          providerId: input.ai.providerId,
          apiKey: typeof input.ai.apiKey === "string" ? input.ai.apiKey.slice(0, 500) : "",
          model: typeof input.ai.model === "string" ? input.ai.model.slice(0, 120) : "",
          baseUrl: typeof input.ai.baseUrl === "string" ? input.ai.baseUrl.slice(0, 300) : "",
        }
      : undefined;
    const codeContext = Array.isArray(input?.codeContext)
      ? input.codeContext.slice(0, 8)
      : [];
    const transcript =
      typeof input?.transcript === "string" ? input.transcript.slice(0, 8000) : "";
    return {
      meeting: {
        id: m.id,
        title: String(m.title).slice(0, 200),
        startedAt: String(m.startedAt ?? ""),
        attendees: Array.isArray(m.attendees) ? m.attendees.slice(0, 20).map(String) : [],
        summary: String(m.summary ?? "").slice(0, 2000),
        decisions: Array.isArray(m.decisions) ? m.decisions.slice(0, 12).map(String) : [],
        actionItems: Array.isArray(m.actionItems)
          ? m.actionItems.slice(0, 16).map((a) => ({
              owner: String(a?.owner ?? "unassigned"),
              text: String(a?.text ?? ""),
            }))
          : [],
        sourceFile: String(m.sourceFile ?? ""),
        platform: m.platform ?? "meeting",
      },
      transcript,
      codeContext,
      ai,
    };
  })
  .handler(async ({ data }): Promise<AnalyzeResult> => {
    const { providerId, apiKey, model, baseUrl } = resolveProvider(data.ai);

    if (!apiKey) {
      return {
        ok: false,
        error: `No API key for ${providerId}. Add one in AI Providers or set the server env key.`,
      };
    }

    const prompt = buildAnalysisPrompt(data.meeting, data.codeContext, data.transcript ?? "");

    try {
      const result =
        providerId === "claude"
          ? await callClaude(apiKey, model, prompt)
          : await callOpenAiCompatible(baseUrl, apiKey, model, prompt);

      const analysis = safeParseAnalysis(result.text, `${providerId}/${result.model}`);
      return { ok: true, analysis };
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Analysis failed";
      return { ok: false, error: msg.slice(0, 300) };
    }
  });
