export const SOURCE_TYPES = [
  "meeting",
  "code_session",
  "slack",
  "whatsapp",
  "readai",
  "zoom",
  "gmeet",
  "teams",
  "git",
] as const;

export type SourceType = (typeof SOURCE_TYPES)[number];

export const CONNECTOR_KINDS = [
  "folder",
  "slack",
  "readai",
  "whatsapp",
  "zoom",
  "gmeet",
  "teams",
  "git",
] as const;

export type ConnectorKind = (typeof CONNECTOR_KINDS)[number];

export const CHUNK_KINDS = ["turn", "summary", "decision", "action", "minutes", "code"] as const;
export type ChunkKind = (typeof CHUNK_KINDS)[number];

export const OAUTH_CONNECTORS = ["slack", "zoom", "gmeet", "teams", "git"] as const;
export type OAuthConnector = (typeof OAUTH_CONNECTORS)[number];

export type Chunk = {
  id: string;
  text: string;
  sourceType: SourceType;
  timestamp: string;
  sourceFile: string;
  documentId: string;
  connectorId: ConnectorKind;
  chunkKind: ChunkKind;
};

export type DocumentRecord = {
  id: string;
  name: string;
  sourceType: SourceType;
  connectorId: ConnectorKind;
  ingestedAt: string;
  chunkCount: number;
  bytes: number;
};

export type ConnectorAuthMode = "none" | "oauth" | "token" | "grok";

export type ConnectorRecord = {
  id: ConnectorKind;
  status: "disconnected" | "connected";
  lastSyncAt: string | null;
  hasSecret: boolean;
  authMode: ConnectorAuthMode;
};

export type ActionItem = {
  owner: string;
  text: string;
};

export type MeetingRepoStatus = "idle" | "searching" | "linked" | "needs_url" | "failed";

export type AnalysisStatus = "idle" | "pending" | "done" | "failed";

export type AnalyzedActionItem = {
  owner: string;
  text: string;
  priority?: "high" | "medium" | "low";
};

export type ProposedPatch = {
  file: string;
  description: string;
  diff: string;
};

/** Fixed-section post-meeting brief generated by the AI provider. */
export type MeetingAnalysis = {
  objective: string;
  topics: string[];
  solutions: string[];
  keyDecisions: string[];
  actionItems: AnalyzedActionItem[];
  technicalImplications: string[];
  proposedPatches: ProposedPatch[];
  risks: string[];
  nextSteps: string[];
  generatedAt: string;
  model: string;
};

export type MeetingRecord = {
  id: string;
  title: string;
  platform: "zoom" | "gmeet" | "teams" | "readai" | "meeting";
  connectorId: ConnectorKind;
  startedAt: string;
  attendees: string[];
  summary: string;
  decisions: string[];
  actionItems: ActionItem[];
  documentId: string;
  sourceFile: string;
  linkedRepoId?: string | null;
  repoStatus?: MeetingRepoStatus;
  repoHint?: string | null;
  repoCandidates?: string[];
  /** Set when the user explicitly marks the meeting as ended. */
  endedAt?: string | null;
  analysisStatus?: AnalysisStatus;
  analysis?: MeetingAnalysis | null;
  analysisError?: string | null;
};

export type RepoOrigin = "github" | "gitlab" | "url" | "upload";

export type RepoRecord = {
  id: string;
  owner: string;
  name: string;
  url: string;
  defaultBranch: string;
  documentId: string;
  indexedAt: string;
  fileCount: number;
  chunkCount: number;
  origin: RepoOrigin;
};

export type QueryRecord = {
  id: string;
  question: string;
  askedAt: string;
  answer: string;
  model: string;
  noRelevantContext: boolean;
  sources: RetrievedChunk[];
};

export type RetrievedChunk = {
  text: string;
  sourceType: SourceType;
  timestamp: string;
  sourceFile: string;
  score: number;
  id: string;
  chunkKind?: ChunkKind;
};

export type ParsedChunk = {
  text: string;
  sourceType: SourceType;
  timestamp: string;
  sourceFile: string;
  chunkKind?: ChunkKind;
};

export const SOURCE_LABELS: Record<SourceType, string> = {
  meeting: "Meeting",
  code_session: "Code session",
  slack: "Slack",
  whatsapp: "WhatsApp",
  readai: "Read AI",
  zoom: "Zoom",
  gmeet: "Google Meet",
  teams: "Teams",
  git: "Git",
};

export const CONNECTOR_LABELS: Record<ConnectorKind, string> = {
  folder: "Transcripts folder",
  slack: "Slack",
  readai: "Read AI",
  whatsapp: "WhatsApp",
  zoom: "Zoom",
  gmeet: "Google Meet",
  teams: "Microsoft Teams",
  git: "Git / Claude Code",
};

export const MINUTES_SOURCE_TYPES: SourceType[] = [
  "zoom",
  "gmeet",
  "teams",
  "readai",
  "meeting",
];

export type RemoteMeeting = {
  title: string;
  startedAt: string;
  attendees: string[];
  summary: string;
  decisions: string[];
  actionItems: ActionItem[];
  transcript: string;
  sourceFile: string;
};

export type GitFile = {
  path: string;
  content: string;
};

export const MAX_CHUNKS = 5000;
export const MAX_CHUNK_CHARS = 4000;
export const DEFAULT_TOP_K = 5;
